### ISSUE TITLE
Resolving syntax error

### ISSUE THREAD

**Issue by tulips8** [rdkcentral/rdkb-halif-ethsw#4]
Goals:

#ifdef FEATURE_RDKB_AUTO_PORT_SWITCH - was missed during the porting of the file

Acceptance Criteria:

- Code changes made to support the switch in the correct place.
- Upgrade TODO to state that switches should not be used in the future
- The file must be tested as building with the rest of the stack.

**Comment by Ulrond** [comment]
resolved due to merge
